// Code generated by "stringer -type=Op"; DO NOT EDIT.

package ipc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpPs-0]
	_ = x[OpStop-1]
	_ = x[OpStart-2]
}

const _Op_name = "OpPsOpStopOpStart"

var _Op_index = [...]uint8{0, 4, 10, 17}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
