name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - readme.md
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - readme.md
      - .gitignore

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x

    - name: build/vet/test
      run: make ci

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3

    - name: fuzz
      run: make fuzz
